export const START_SOLVING = 'START_SOLVING';
export const CANCEL_SOLVING = 'CANCEL_SOLVING';
export const DRAW_PARTIAL_SOLUTION = 'DRAW_PARTIAL_SOLUTION';
export const DRAW_SOLUTION = 'DRAW_SOLUTION';
